# Generated by Django 4.2.1 on 2023-05-23 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents')),
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4)),
            ],
        ),
    ]
